<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="IqChannelizer.Benchmarks" />
    <InternalsVisibleTo Include="IqChannelizer.Tests" />
  </ItemGroup>
  <ItemGroup>
    <None Update="fftw3f\libfftw3f-3.dll">
      <Link>libfftw3f-3.dll</Link>
      <TargetPath>libfftw3f-3.dll</TargetPath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <Pack>false</Pack>
    </None>
    <None Update="fftw3f\fftw3.h" Pack="false" />
  </ItemGroup>
</Project>
